# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  slack: circleci/slack@3.4.2
  browser-tools: circleci/browser-tools@1.1.1
executors:
  ci:
    working_directory: /workspace
    docker:
      - image: ghcr.io/csu-booking-platform/devcontainer:0.0.6
        command: [ ]
  ci-db:
    working_directory: /workspace
    docker:
      - image: ghcr.io/csu-booking-platform/devcontainer:0.0.6
        command: [ ]
      - image: circleci/postgres:10.15
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: circle_test
          POSTGRES_PASSWORD: passw0rd
jobs:
  validate-commits:
    docker:
      - image: docker.io/alexstojda/commitlint:11.0.0
    steps:
      - checkout
      - run:
          name: Analyze commits starting from << pipeline.git.base_revision >>
          command: commitlint --from << pipeline.git.base_revision >>
  tag-and-release:
    executor: ci
    environment:
      GITHUB_OWNER: csu-booking-platform
      GITHUB_REPO: application
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "59:17:eb:0c:20:36:e3:54:b2:54:84:68:b1:79:b4:ab"
      - checkout
      - run:
          name: Get next version
          command: |
            curl -L https://github.com/idc101/git-mkver/releases/download/v1.1.1/git-mkver-linux-amd64-1.1.1.tar.gz | tar xvz
            sudo mv git-mkver /usr/local/bin
            git mkver next -t
            if [ $(git tag -l "$(git mkver next -t)") ]; then
              circleci-agent step halt
            else
              echo "export TAG=$(git mkver next -t)" >> $BASH_ENV
            fi
      # Insert commands to build & publish app & assets
      - run:
          name: Create Release
          command: |
            wget https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2
            bzip2 -d linux-amd64-github-release.bz2
            chmod +x linux-amd64-github-release
            mv linux-amd64-github-release ghr
            git mkver tag
            git push --tags
            ./ghr release \
              --tag $TAG \
              --security-token $GITHUB_TOKEN \
              --user $GITHUB_OWNER \
              --repo $GITHUB_REPO

      - slack/status:
          fail_only: true
  test-php:
    executor: ci-db
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Prepare Environment"
          command: |
            echo -e "xdebug.mode=coverage" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: "Run migrations & seed"
          command: php artisan migrate:fresh --seed
      - run:
          name: "Run Unit Tests"
          command: php artisan test --filter Unit.
      - run:
          name: "Run Feature Tests"
          command: php artisan test --filter Feature.
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: tests/Browser/screnshots
      - store_artifacts:
          path: tests/Browser/console
      - store_artifacts:
          path: storage/logs/laravel.log
      - persist_to_workspace:
          root: .
          paths:
            - reports
  test-php-browser:
    executor: ci-db
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Prepare Environment"
          command: |
            echo -e "xdebug.mode=coverage" | sudo tee /usr/local/etc/php/php.ini > /dev/null
      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && sudo tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: "Install Dusk and Update Chrome Drivers"
          command: "php artisan dusk:update --detect"
      - run:
          name: Start Chrome Driver
          command: ./vendor/laravel/dusk/bin/chromedriver-linux --allowed-ips
          background: true
      - run:
          name: Run Laravel Server
          command: php artisan serve
          background: true
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run:
          name: "Run migrations & seed"
          command: php artisan migrate:fresh --seed
      - run:
          name: "Run Tests"
          command: php artisan test --filter Browser
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - store_artifacts:
          path: tests/Browser/screnshots
      - store_artifacts:
          path: tests/Browser/console
      - store_artifacts:
          path: storage/logs/laravel.log
      - persist_to_workspace:
          root: .
          paths:
            - reports

  test-js:
    executor: ci
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Run Tests"
          command: npm run test-ci
      - store_test_results:
          path: reports
      - store_artifacts:
          path: reports
      - persist_to_workspace:
          root: .
          paths:
            - reports

  sonar:
    executor: ci
    steps:
      - attach_workspace:
          at: .
      - sonarcloud/scan
      - persist_to_workspace:
          root: .
          paths:
            - .

  build:
    executor: ci

    steps:
      - checkout
      - run:
          name: "Create Environment file"
          command: |
            mv .env.ci .env
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Backend Dependencies"
          command: composer install -n --prefer-dist

      - run:
          name: "Generate app key"
          command: php artisan key:generate --ansi

      - run:
          name: "Install Frontend Dependencies"
          command: npm ci

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.lock" }}-{{ checksum "package-lock.json" }}
          paths:
            - ./vendor
            - ./node_modules

      - run:
          name: "Build Frontend Assets"
          command: npm run prod

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - persist_to_workspace:
          root: .
          paths:
            - .

workflows:
  build:
    jobs:
      - build
      - test-php:
          requires:
            - build
      - test-php-browser:
          requires:
            - build
      - test-js:
          requires:
            - build
      - sonar:
          requires:
            - test-php
            - test-js
      - validate-commits:
          filters:
            branches:
              # only from forks
              only:
                - /^pull\/.*$/
      - tag-and-release:
          requires:
            - sonar
          filters: # using regex filters requires the entire branch to match
            branches:
              only: # only branches matching the below regex filters will run
                - main
