# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#

version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.2
  slack: circleci/slack@3.4.2
jobs:
  tag-and-release:
    docker:
      - image: cimg/base:2020.01
    environment:
      TAG_FORMAT: "{Major}.{Minor}.{Patch}"
      GITHUB_OWNER: csu-booking-platform
      GITHUB_REPO: application
    steps:
      - run:
          name: Get next version
          command: |
            curl -L https://github.com/idc101/git-mkver/releases/download/v1.1.1/git-mkver-linux-amd64-1.1.1.tar.gz | tar xvz
            sudo mv git-mkver /usr/local/bin
            git mkver next -f $TAG_FORMAT >> GIT_TAG
            if [ $(git tag -l "$(cat GIT_TAG)") ]; then
              circleci-agent step halt
            else
              echo "export TAG=$(cat GIT_TAG)" >> $BASH_ENV
            fi
      # Insert commands to build & publish app & assets
      - run:
          name: Create Release
          command: |
            wget https://github.com/github-release/github-release/releases/download/v0.8.1/linux-amd64-github-release.bz2
            bzip2 -d linux-amd64-github-release.bz2
            chmod +x linux-amd64-github-release
            mv linux-amd64-github-release ghr
            ./ghr release \
              --tag $TAG \
              --security-token $GITHUB_TOKEN \
              --user $GITHUB_OWNER \
              --repo $GITHUB_REPO
  build:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4-node-browsers

    steps:
      - checkout

      - run:
          name: "Prepare Environment"
          command: |
            sudo apt update
            sudo docker-php-ext-install zip
      - run:
          name: "Create Environment file"
          command: |
            mv .env.example .env
      # Download and cache dependencies
      - restore_cache:
          keys:
            # "composer.lock" can be used if it is committed to the repo
            - v1-dependencies-{{ checksum "composer.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: "Install Backend Dependencies"
          command: composer install -n --prefer-dist

      - run:
          name: "Install Frontend Dependencies"
          command: npm ci

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run:
          name: "Generate App key"
          command: php artisan key:generate

      - run:
          name: "Run Unit Tests"
          command: php artisan test

      - sonarcloud/scan

      - run:
          name: "Build Frontend Assets"
          command: npm run prod

      - slack/status:
          fail_only: true

workflows:
  build:
    jobs:
      - build
      - tag-and-release:
          filters:  # using regex filters requires the entire branch to match
            branches:
              only:  # only branches matching the below regex filters will run
                - main
