version: '3'

services:
  app:
    image: ghcr.io/csu-booking-platform/devcontainer:0.0.4

    volumes:
      - ..:/workspace:cached

    ports:
     - 8080:8080
     - 3000:3000
     - 5432:5432
     - 1025:1025
     - 8025:8025
    # Uncomment the next line to use a non-root user for all processes.
    # user: vscode

    # Use "forwardPorts" in **devcontainer.json** to forward an app port locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: laravel
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    # Runs app on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app
    # Add "forwardPorts": ["5432"] to **devcontainer.json** to forward Postgres locally.
    # (Adding the "ports" property to this file will not forward from a Codespace.)

  mail:
    image: mailhog/mailhog

    # Runs app on the same network as the app container, allows "forwardPorts" in devcontainer.json function.
    network_mode: service:app

volumes:
  postgres-data:
